export const STUDENTS_ACTION_TYPES = {
  FETCH_STUDENTS_START: 'student/FETCH_STUDENTS_START',
  FETCH_STUDENTS_SUCCESS: 'student/FETCH_STUDENTS_SUCCESS',
  FETCH_STUDENTS_FAILED: 'student/FETCH_STUDENTS_FAILED',

  UPDATE_STUDENT_START: 'student/UPDATE_STUDENT_START',
  UPDATE_STUDENT_SUCCESS: 'student/UPDATE_STUDENT_SUCCESS',
  UPDATE_STUDENT_FAILED: 'student/UPDATE_STUDENT_FAILED',
};
