export const STUDENTS_ACTION_TYPES = {
  FETCH_STUDENTS_START: 'student/FETCH_STUDENTS_START',
  FETCH_STUDENTS_SUCCESS: 'student/FETCH_STUDENTS_SUCCESS',
  FETCH_STUDENTS_FAILED: 'student/FETCH_STUDENTS_FAILED',

  ADD_STUDENT_START: 'student/ADD_STUDENT_START',
  ADD_STUDENT_SUCCESS: 'student/ADD_STUDENT_SUCCESS',
  ADD_STUDENT_FAILED: 'student/ADD_STUDENT_FAILED',

  UPDATE_STUDENT_START: 'student/UPDATE_STUDENT_START',
  UPDATE_STUDENT_SUCCESS: 'student/UPDATE_STUDENT_SUCCESS',
  UPDATE_STUDENT_FAILED: 'student/UPDATE_STUDENT_FAILED',

  DELETE_STUDENT_START: 'student/DELETE_STUDENT_START',
  DELETE_STUDENT_SUCCESS: 'student/DELETE_STUDENT_SUCCESS',
  DELETE_STUDENT_FAILED: 'student/DELETE_STUDENT_FAILED',
};
