export const PROJECTS_ACTION_TYPES = {
  FETCH_PROJECTS_START: 'project/FETCH_PROJECTS_START',
  FETCH_PROJECTS_SUCCESS: 'project/FETCH_PROJECTS_SUCCESS',
  FETCH_PROJECTS_FAILED: 'project/FETCH_PROJECTS_FAILED',

  ADD_PROJECT_START: 'project/ADD_PROJECT_START',
  ADD_PROJECT_SUCCESS: 'project/ADD_PROJECT_SUCCESS',
  ADD_PROJECT_FAILED: 'project/ADD_PROJECT_FAILED',

  UPDATE_PROJECT_START: 'project/UPDATE_PROJECT_START',
  UPDATE_PROJECT_SUCCESS: 'project/UPDATE_PROJECT_SUCCESS',
  UPDATE_PROJECT_FAILED: 'project/UPDATE_PROJECT_FAILED',

  DELETE_PROJECT_START: 'project/DELETE_PROJECT_START',
  DELETE_PROJECT_SUCCESS: 'project/DELETE_PROJECT_SUCCESS',
  DELETE_PROJECT_FAILED: 'project/DELETE_PROJECT_FAILED',
};
